### ISSUE TITLE
target pattern contains no '%'.

### ISSUE THREAD

**Issue by Narek-939** [berndpfrommer/basalt_ros#6]
Starting >>> basalt_ros
[Processing: basalt_ros]                            
[Processing: basalt_ros]                                    
--- stderr: basalt_ros                                        
CMakeFiles/vio_utils.dir/build.make:82: *** target pattern contains no '%'.  Stop.
make[1]: *** [CMakeFiles/Makefile2:336: CMakeFiles/vio_utils.dir/all] Error 2
make[1]: *** Waiting for unfinished jobs....
CMakeFiles/test_subscriber.dir/build.make:97: *** target pattern contains no '%'.  Stop.
make[1]: *** [CMakeFiles/Makefile2:228: CMakeFiles/test_subscriber.dir/all] Error 2
CMakeFiles/get_calibration.dir/build.make:82: *** target pattern contains no '%'.  Stop.
make[1]: *** [CMakeFiles/Makefile2:282: CMakeFiles/get_calibration.dir/all] Error 2
/usr/bin/ld: warning: libopencv_imgcodecs.so.4.2, needed by /opt/ros/foxy/lib/libcv_bridge.so, may conflict with libopencv_imgcodecs.so.4.5
/usr/bin/ld: warning: libopencv_imgproc.so.4.2, needed by /opt/ros/foxy/lib/libcv_bridge.so, may conflict with libopencv_imgproc.so.4.5
/usr/bin/ld: warning: libopencv_core.so.4.2, needed by /opt/ros/foxy/lib/libcv_bridge.so, may conflict with libopencv_core.so.4.5
make: *** [Makefile:141: all] Error 2
---
Failed   <<< basalt_ros [1min 24s, exited with code 2]

how to fix this problem, or please give me some kind of guidance, which can help me.

**Comment by berndpfrommer** [comment]
What OS and ROS version are you using?

**Comment by Narek-939** [comment]
I am using Jetpack 5.1.2 ubuntu 20.04 based OS with ros2 foxy

**Comment by Narek-939** [comment]
I found the solution, and this error because of the names of directories 
https://stackoverflow.com/questions/15113138/target-pattern-contains-no-makefile

**Comment by Narek-939** [comment]
but I dont know what I need to change in CMakeFiles to generate right make files)

**Comment by berndpfrommer** [comment]
Ah, you are running on a Jetson?
I have a AGX xavier (currently not accessible to me though) running Ubuntu 20.04 + Galactic that I could try to compile on. But it should work. After all, it builds in the docker container for the Continuous Integration.
Why do you think the directory name is an issue? Would you mind posting the path of your workspace, i.e. ``pwd`` at the top of your workspace? Do other ROS packages build fine in that workspace?

**Comment by Narek-939** [comment]
Yes I have two packages which are built successfully, but in basalt_ros files which generate make files they work not correctly, because in my build directory of basalt_ros made the directory named "vio_utils.dir" "vio_frontend_node.dir" and others, and when these folders using in other files, there are some issues about path because that paths contain "." in directory name, I this read in stackoverflow, this is link of issue https://stackoverflow.com/questions/15113138/target-pattern-contains-no-makefile, so I want to find solution to change make generator files to make this file names without "."

thanks)

**Comment by Narek-939** [comment]
This is a badly written error message from Make. It means "one of your filenames had a character that could be part of a regular expression". Make is very naive about filesystems and quoting. It doesn't believe that:

foo:  'The bar.'

refers to a literal string. It takes The as one word, bar. as another word, and then barfs on the period. Do this instead:

foo:  The\ bar\.

**Comment by Narek-939** [comment]
this is the answer, how to fix)

**Comment by berndpfrommer** [comment]
I don't think that the problem is with the name of the directory. On my machine it builds just fine with the same directory name pattern (see below). The repository also builds fine in the continuous integration build environment.

```
./basalt_ros/CMakeFiles/vio_utils.dir
./basalt_ros/CMakeFiles/vio_utils.dir/depend.make
./basalt_ros/CMakeFiles/vio_utils.dir/build.make
./basalt_ros/CMakeFiles/vio_utils.dir/compiler_depend.ts
./basalt_ros/CMakeFiles/vio_utils.dir/flags.make
./basalt_ros/CMakeFiles/vio_utils.dir/compiler_depend.internal
./basalt_ros/CMakeFiles/vio_utils.dir/src
./basalt_ros/CMakeFiles/vio_utils.dir/src/utils.cpp.o.d
./basalt_ros/CMakeFiles/vio_utils.dir/src/utils.cpp.o
./basalt_ros/CMakeFiles/vio_utils.dir/DependInfo.cmake
./basalt_ros/CMakeFiles/vio_utils.dir/compiler_depend.make
./basalt_ros/CMakeFiles/vio_utils.dir/progress.make
./basalt_ros/CMakeFiles/vio_utils.dir/link.txt
./basalt_ros/CMakeFiles/vio_utils.dir/cmake_clean.cmake
./basalt_ros/libvio_utils.so
```

**Comment by Narek-939** [comment]
I built it in the past on my other computer, and everything is ok, but this problem because of make, it depends on cmake and make version also, so I want to change CMakeLists.txt to generate directories with other names to avoid this issue, and I will be glad to any guidance)

**Comment by Narek-939** [comment]
I added this code to my CMakeLists.txt 
#####################################################################
add_custom_command(TARGET vio_utils POST_BUILD
    COMMAND ${CMAKE_COMMAND} -E rename "${CMAKE_BINARY_DIR}/CMakeFiles/vio_utils.dir" "${CMAKE_BINARY_DIR}/CMakeFiles/vio_utils_dir"
    COMMENT "Renaming output folder for vio_utils"
)
#####################################################################
and everything is OK, so I think that it depends on OS and which version of cmake I use, Thank you very much to answer to my question)

**Comment by berndpfrommer** [comment]
Nice job! Sorry I couldn't be of more help. I'm not much of a cmake wizard.
